name: "Build and Deploy Lucira Website"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Install dependencies if needed (only if you're using a build tool)
      - name: Install Dependencies
        run: npm install  # Modify this if you have JS or CSS build dependencies.

      # Build the website (optional, depending on your setup)
      - name: Build the Website
        run: npm run build  # Remove if you don't use a build tool.

      # Deploy to Ionos without a config file
      - name: Deploy to Ionos
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 8171c7b2-6a2d-43d8-a65e-a564e97ac4bc
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: lucira-website/  # Path to your website files
          action: upload  # Only uploads the files to Ionos
